version: "3"

services:
  quake3:
    build: .
    restart: always
    ports:
     - 27960:27960/udp
    volumes:
     - ./autoexec.cfg:/home/ioq3srv/ioquake3/baseq3/autoexec.cfg
     - ./server-baseq3.cfg:/home/ioq3srv/ioquake3/baseq3/server-baseq3.cfg
     - log-volume:/home/ioq3srv/.q3a/baseq3/logs

  ng-quake3-be:
    environment:
       - Q3SERV_HOST:quake3
       - Q3LOG_FILE:logs/server.log

    build: ./ng-quake3-be/
    restart: always
    volumes:
      - ./all_maps.json:/var/q3-server-docker-rest-api/lib/api/maps/maps.json
      - log-volume:/var/q3-server-docker-rest-api/logs
    ports:
      - 9009:9009

  ng-quake3-fe:
    restart: always
    build: ./ng-quake3-fe/
    ports:
     - 8080:8080

  mattermost-webhook:
    build: ./mattermost-webhook/
    restart: always
    environment:
      - REST_API_HOST:ng-quake3-be
      - REST_API_PORT:9009

  map-download:
    restart: always
    build: ./map-download
    ports:
      - 9090:9090
volumes:
     log-volume:
