version: "3"

services:
  quake3:
    build: .
    restart: always
    ports:
     - 27960:27960/udp
    volumes:
     - ./server.cfg:/home/ioq3srv/ioquake3/baseq3/server.cfg
     - ./levels.cfg:/home/ioq3srv/ioquake3/baseq3/levels.cfg
    command: ["+exec", "server.cfg", "+exec", "levels.cfg"]

  ng-quake3-be:
    environment:
       - Q3SERV_HOST:quake3
       
    build: ./ng-quake3-be/
    restart: always
    volumes:
      - ./all_maps.json:/var/q3-server-docker-rest-api/lib/api/maps/maps.json
    ports:
      - 9009:9009

  ng-quake3-fe:
    restart: always
    build: ./ng-quake3-fe/
    ports:
     - 8080:8080

  map-download:
    restart: always
    build: ./map-download
    ports:
      - 9090:9090
